### ISSUE TITLE
Object literals don't handle indentation intuitively

### ISSUE THREAD

**Issue by praxiq** [jashkenas/coffeescript#1118]
The documentation gives this example of specifying object literals:

```
kids =
  brother: 
    name: 'Max'
    age: 11
  sister:
    name: 'Ida'
    age: 9
```

This slightly shortened form works too:

```
kids =
  brother: 
    name: 'Max', age: 11
  sister: 
    name: 'Ida', age: 9
```

Both translate to the following javascript:

```
var kids;
kids = {
  brother: {
    name: 'Max',
    age: 11
  },
  sister: {
    name: 'Ida',
    age: 9
  }
};
```

One might reasonably expect this even more compact form to work as well:

```
kids =
  brother: name: 'Max', age: 11
  sister: name: 'Ida', age: 9
```

However, that translates to something very different:

```
var kids;
kids = {
  brother: {
    name: 'Max',
    age: 11,
    sister: {
      name: 'Ida',
      age: 9
    }
  }
};
```

`brother` and `sister` are at the same level of indentation, but coffeescript interprets one as a child of the other. I can't think of any circumstance in which this would be what the user intended. I would expect this behavior only if `sister` were indented.
