### ISSUE TITLE
Object extension literal

### ISSUE THREAD

**Issue by itrelease** [jashkenas/coffeescript#2176]
https://github.com/itrelease/coffee-script/commit/19976dc76799f7f7a0507def5af455cf17d7ef2e

Never give up ;) add object extension literal (http://wiki.ecmascript.org/doku.php?id=harmony:object_literals#object_extension_literal) so now it's possible to do this thing:

```
kids =
  brother1:
    name: "Max"
    age:  11

kids .=
  sister:
    name: "Ida"
    age:  9
  brother2:
    name: "Neal"
    age: 10
```

and cs generate this code:

```
(function() {
  var kids;

  kids = {
    brother1: {
      name: "Max",
      age: 11
    }
  };

  kids["sister"] = {
    name: "Ida",
    age: 9
  };
  kids["brother2"] = {
    name: "Neal",
    age: 10
  };

}).call(this);
```
