### ISSUE TITLE
broken destrcutive assignments when retreiving arguments

### ISSUE THREAD

**Issue by xh3b4sd** [jashkenas/coffeescript#2621]
Given the following object it is not possible to retreive function arguments using destrcutive assignments if nesting is deep. The workaround works, but it would be more pretty to be able to use destrcutive assignments directly.

```
object =
  prop1:
    key1: "value1"
    key2: "value2"
  prop2:
    key1: "value1"
    key2: "value2"
```

```
# That works!
method = (obj) ->
  { prop1: { key1 }, prop2: { key2 } } = obj
  console.log key1
  console.log key2
method(object)
```

If you run the following code it will ends up in an compiling error named `SyntaxError: In bug.coffee, multiple parameters named 'undefined' at SyntaxError (unknown source)`

```
methodError = ({ prop1: { key1 }, prop2: { key2 } }) ->
  console.log key1
  console.log key2
methodError(object)
```
