### ISSUE TITLE
cannot place comment line before ajaxPost

### ISSUE THREAD

**Issue by atitusfwd** [jashkenas/coffeescript#2916]
This issue is present with 1.6.2 and with the online interpreter.  If you try to put a comment line immediately before an ajaxPost then it will fail to compile with UNEXPECTED CALL_START.  This does not happen with previous version 1.4;  I do not know exactly which release where it was broken.  Here is example code that will not compile: 

```
class TestClass
    methodA: (b) ->
        ### comment ###
        ajaxPost
            type: "POST"
            url: "test"
            data:
                method_name: "abc123"
                inValue: b
            success: (data) ->
                ### any statement here ###
                a = 1 + 2
            dataType: "json"
```
