### ISSUE TITLE
Site issue: code blocks twitch on hover

### ISSUE THREAD

**Issue by Inve1951** [jashkenas/coffeescript#5448]
There's a new visual issue with https://coffeescript.org.

The first time you hover some code block CodeMirror kicks in. When it does that it incorrectly overrides a CSS rule.

```css
/* before */
.CodeMirror pre {
    line-height: 1.4em;
}

/* after */
.CodeMirror pre.CodeMirror-line {
    line-height: inherit;
}
```

On my device this reduces the effective line height from `19.6px` to `17.5px`, shrinking the vertical size of the code block.

But there's something else wrong too. Even with that rule disabled, most of the time CodeMirror kicks in, the container grows `1px` in height.

Tested on Firefox.
